// Site-wide constants for RJ Power Solutions
// Replace with actual details before going live

export const SITE = {
  name: "RJ Power Solutions",
  tagline: "Power Your Future with Smart Solar Solutions",
  phone: "+91-98765-43210",
  phoneRaw: "919876543210",
  whatsapp: "919876543210",
  email: "info@rjpowersolutions.in",
  address: "123, Solar Street, Vijay Nagar, Indore, MP 452010",
  addressShort: "Vijay Nagar, Indore, MP",
  timings: "Mon–Fri: 9 AM – 6 PM | Sat: 9 AM – 2 PM",
  stats: [
    { value: "500+", label: "Installations Done" },
    { value: "5+", label: "Years Experience" },
    { value: "100%", label: "Quality Components" },
    { value: "98%", label: "On-Time Delivery" },
  ],
} as const;

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Services", href: "/services" },
  { label: "Projects", href: "/projects" },
  { label: "Calculator", href: "/calculator" },
  { label: "EMI & Subsidy", href: "/emi-subsidy" },
  { label: "FAQ", href: "/faq" },
  { label: "Contact", href: "/contact" },
] as const;

export const SERVICES = [
  {
    slug: "residential",
    title: "Residential Solar",
    icon: "Home",
    shortDesc: "Perfect solar solutions for homes and villas.",
    desc: "Transform your home with rooftop solar panels and eliminate your electricity bills forever.",
    benefits: [
      "Eliminate electricity bills by up to 90%",
      "Government subsidy of ₹18,000–₹78,000 available",
      "System lifespan of 25+ years",
      "Free site survey and design",
      "Hassle-free installation in 1–3 days",
      "Net metering support for bill credits",
    ],
    process: [
      { step: "Site Survey", desc: "Free rooftop assessment and shadow analysis" },
      { step: "Custom Design", desc: "Tailored system design for your consumption" },
      { step: "Subsidy Application", desc: "Assistance with PM Surya Ghar subsidy" },
      { step: "Installation", desc: "Professional installation by certified technicians" },
      { step: "Net Metering", desc: "Grid connection and net metering setup" },
      { step: "Monitoring", desc: "App-based real-time performance monitoring" },
    ],
    color: "orange",
  },
  {
    slug: "commercial",
    title: "Commercial Solar",
    icon: "Building2",
    shortDesc: "Cut operational costs for offices, malls & shops.",
    desc: "Reduce your commercial electricity expenses with high-efficiency solar systems designed for business needs.",
    benefits: [
      "Reduce operational costs by 40–70%",
      "Accelerated depreciation tax benefits",
      "Custom capacity from 10 kW to 1 MW",
      "Priority installation and dedicated support",
      "ROI within 3–5 years",
      "Enhanced brand image with green credentials",
    ],
    process: [
      { step: "Energy Audit", desc: "Detailed consumption analysis" },
      { step: "Financial Modeling", desc: "ROI and savings projection" },
      { step: "System Design", desc: "High-efficiency commercial array design" },
      { step: "Procurement", desc: "Premium panels and inverters sourced" },
      { step: "Installation", desc: "Zero business disruption installation" },
      { step: "Commissioning", desc: "Testing and handover with training" },
    ],
    color: "blue",
  },
  {
    slug: "industrial",
    title: "Industrial Solar",
    icon: "Factory",
    shortDesc: "Massive savings for factories and warehouses.",
    desc: "Large-scale solar installations for industries, factories, and manufacturing plants to slash power costs.",
    benefits: [
      "Save ₹5–50 lakhs annually on power bills",
      "Scale up to multi-MW installations",
      "Reduce carbon footprint and ESG compliance",
      "Open access and group captive options",
      "Dedicated project management team",
      "25-year performance warranty",
    ],
    process: [
      { step: "Load Analysis", desc: "Industrial consumption pattern study" },
      { step: "Technical Assessment", desc: "Structural and electrical evaluation" },
      { step: "Project Planning", desc: "Timeline and milestone planning" },
      { step: "Procurement", desc: "Bulk sourcing of premium components" },
      { step: "EPC Execution", desc: "End-to-end project delivery" },
      { step: "O&M", desc: "Ongoing operations and maintenance" },
    ],
    color: "orange",
  },
  {
    slug: "maintenance",
    title: "Solar Maintenance",
    icon: "Wrench",
    shortDesc: "Keep your system performing at peak efficiency.",
    desc: "Professional maintenance services to ensure your solar investment delivers maximum returns year after year.",
    benefits: [
      "Annual maintenance contract (AMC) plans",
      "Performance monitoring and alerts",
      "Preventive and corrective maintenance",
      "Inverter service and replacement",
      "Wiring and junction box inspection",
      "Performance report and optimization",
    ],
    process: [
      { step: "Inspection", desc: "Visual and electrical inspection" },
      { step: "Cleaning", desc: "Professional panel cleaning" },
      { step: "Testing", desc: "I-V curve and performance testing" },
      { step: "Repairs", desc: "Fault diagnosis and repair" },
      { step: "Optimization", desc: "MPPT tuning and tilt adjustment" },
      { step: "Reporting", desc: "Detailed performance report" },
    ],
    color: "blue",
  },
  {
    slug: "cleaning",
    title: "Panel Cleaning",
    icon: "Sparkles",
    shortDesc: "Boost output by 20–30% with expert cleaning.",
    desc: "Dust and bird droppings can cut solar output by up to 30%. Our expert cleaning restores full efficiency.",
    benefits: [
      "Restore up to 30% lost output",
      "Deionized water for spot-free results",
      "Soft brush anti-scratch cleaning",
      "Early damage detection",
      "Bi-annual cleaning recommended",
      "Affordable per-panel pricing",
    ],
    process: [
      { step: "Assessment", desc: "Soiling and damage check" },
      { step: "Water Treatment", desc: "Purified water preparation" },
      { step: "Soft Brushing", desc: "Gentle anti-scratch panel cleaning" },
      { step: "Rinse", desc: "Spot-free deionized water rinse" },
      { step: "Inspection", desc: "Post-clean performance check" },
      { step: "Report", desc: "Before/after output comparison" },
    ],
    color: "orange",
  },
  {
    slug: "net-metering",
    title: "Net Metering",
    icon: "Zap",
    shortDesc: "Sell surplus power back to the grid.",
    desc: "Complete assistance with net metering applications to earn bill credits by exporting excess solar energy.",
    benefits: [
      "Full application and paperwork assistance",
      "Coordination with MPESZ discom",
      "Bi-directional meter installation",
      "Track exports and earn credits",
      "Zero electricity bill possible",
      "Government compliance assurance",
    ],
    process: [
      { step: "Eligibility Check", desc: "Verify net metering eligibility" },
      { step: "Documentation", desc: "Prepare all required documents" },
      { step: "Application", desc: "File application with discom" },
      { step: "Inspection", desc: "Coordinate discom site visit" },
      { step: "Meter Install", desc: "Bi-directional meter setup" },
      { step: "Activation", desc: "Net metering goes live" },
    ],
    color: "blue",
  },
] as const;

export const FAQS = [
  {
    q: "How much does a solar system cost in Indore?",
    a: "A 1 kW residential solar system costs approximately ₹60,000–₹75,000 before subsidy. With the PM Surya Ghar Muft Bijli Yojana subsidy, you can receive ₹18,000 for 1 kW, ₹30,000 for 2 kW, and ₹78,000 for 3 kW systems. Most 3–5 kW home systems cost ₹1.5–₹3.5 lakh after subsidy.",
  },
  {
    q: "How long do solar panels last?",
    a: "Quality solar panels come with a 25-year performance warranty, guaranteeing at least 80% output efficiency after 25 years. The actual lifespan can be 30–35 years. Inverters typically last 10–15 years and may need replacement once during the panel lifetime.",
  },
  {
    q: "What maintenance is required?",
    a: "Solar panels are very low maintenance. We recommend bi-annual cleaning to maintain peak efficiency (dust reduces output by 15–25%). An annual electrical inspection is also advisable. Our AMC plans cover all maintenance needs at a predictable cost.",
  },
  {
    q: "Is government subsidy available in Madhya Pradesh?",
    a: "Yes! The PM Surya Ghar Muft Bijli Yojana provides direct subsidies of ₹18,000/kW (up to 2 kW) and ₹9,000/kW (for 2–3 kW). Maximum subsidy is ₹78,000 for a 3 kW system. We handle the complete subsidy application process for you.",
  },
  {
    q: "What is net metering?",
    a: "Net metering allows you to export surplus solar energy to the grid and receive electricity credits on your bill. When your panels produce more than you consume, the excess units are credited. When you need more, you draw from the grid. This effectively gives you a 'solar bank account' to minimize your bills.",
  },
  {
    q: "How much can I save on electricity bills?",
    a: "Savings depend on your system size and current consumption. A well-sized system typically reduces bills by 70–90%. A household spending ₹3,000/month can save ₹25,000–₹30,000 per year. Over 25 years, total savings can exceed ₹6–8 lakhs on a system worth ₹1.5–2 lakhs.",
  },
  {
    q: "How long does installation take?",
    a: "A typical residential rooftop installation takes 1–3 days. Commercial installations may take 1–2 weeks depending on capacity. We ensure minimal disruption to your daily routine during installation.",
  },
  {
    q: "What is the payback period for solar?",
    a: "The payback period for a residential solar system in Indore is typically 3–5 years with the government subsidy. Commercial systems often pay back in 3–4 years due to higher electricity tariffs and depreciation benefits. After payback, you enjoy free electricity for 20+ years.",
  },
] as const;

export const TESTIMONIALS = [
  {
    name: "Rajesh Sharma",
    location: "Vijay Nagar, Indore",
    rating: 5,
    text: "RJ Power Solutions transformed our home's energy consumption. Our electricity bill dropped from ₹4,500 to under ₹200 per month. The installation team was professional and completed the work in just 2 days. Highly recommended!",
    property: "3 kW Residential",
    avatar: "RS",
  },
  {
    name: "Priya Malhotra",
    location: "Scheme 54, Indore",
    rating: 5,
    text: "Excellent service from start to finish. They handled everything including the government subsidy application. We received ₹78,000 subsidy and our net investment was very reasonable. The savings are real and significant!",
    property: "3 kW Residential",
    avatar: "PM",
  },
  {
    name: "Amit Joshi",
    location: "Palasia, Indore",
    rating: 5,
    text: "We installed a 25 kW system for our factory. The ROI calculation they provided was accurate and we've been saving over ₹40,000 per month since commissioning. Their after-sales support is exceptional.",
    property: "25 kW Industrial",
    avatar: "AJ",
  },
  {
    name: "Sunita Patel",
    location: "Nipania, Indore",
    rating: 5,
    text: "Very transparent pricing and no hidden costs. The solar savings calculator they provided was accurate. I save ₹2,800 every month. Best investment I've made for my home!",
    property: "2 kW Residential",
    avatar: "SP",
  },
  {
    name: "Vikram Agarwal",
    location: "AB Road, Indore",
    rating: 5,
    text: "Our commercial building now generates solar power for all 12 floors. The project was completed on time and within budget. RJ Power Solutions truly delivered on their promises. Zero electricity cost for common areas!",
    property: "50 kW Commercial",
    avatar: "VA",
  },
  {
    name: "Deepika Rathore",
    location: "MR-9, Indore",
    rating: 5,
    text: "The team at RJ Power Solutions is knowledgeable and patient. They explained everything clearly and helped with net metering registration. Within 3 months, I could see the savings clearly in my bills.",
    property: "3 kW Residential",
    avatar: "DR",
  },
] as const;

export const PROJECTS = [
  {
    id: 1,
    title: "Sharma Residence",
    category: "residential",
    capacity: "5 kW",
    location: "Vijay Nagar, Indore",
    time: "2 Days",
    savings: "₹3,500/month",
    image: "/gallery-residential-1.png",
  },
  {
    id: 2,
    title: "Sunrise Commercial Complex",
    category: "commercial",
    capacity: "50 kW",
    location: "AB Road, Indore",
    time: "8 Days",
    savings: "₹35,000/month",
    image: "/gallery-commercial-1.png",
  },
  {
    id: 3,
    title: "Joshi Industries",
    category: "industrial",
    capacity: "200 kW",
    location: "Pithampur, Indore",
    time: "3 Weeks",
    savings: "₹1.2 Lakh/month",
    image: "/gallery-industrial-1.png",
  },
  {
    id: 4,
    title: "Patel Villa",
    category: "residential",
    capacity: "3 kW",
    location: "Scheme 54, Indore",
    time: "1 Day",
    savings: "₹2,200/month",
    image: "/gallery-residential-2.png",
  },
  {
    id: 5,
    title: "City School Indore",
    category: "commercial",
    capacity: "30 kW",
    location: "Nipania, Indore",
    time: "5 Days",
    savings: "₹20,000/month",
    image: "/gallery-school-1.png",
  },
  {
    id: 6,
    title: "Metro Mall Rooftop",
    category: "commercial",
    capacity: "100 kW",
    location: "Palasia, Indore",
    time: "12 Days",
    savings: "₹70,000/month",
    image: "/gallery-commercial-2.png",
  },
] as const;

export const whatsappLink = (message: string) =>
  `https://wa.me/${SITE.whatsapp}?text=${encodeURIComponent(message)}`;
